---
title: "Culture versus Sylph & Kraken Analysis"
author: "Thy Nguyen"
date: "`r Sys.Date()`"
output: html_document
---

```{r Load packages, include=FALSE}
library(tidyverse)
library(readxl)
library(readr)
library(ggplot2)
library(dplyr)
library(janitor)
library(ComplexUpset)
library(ggpubr)

setwd("/Users/thynguyen/Documents/GitHub/SkinBioassayStudy/Figures/Final/FigureS1_CulturevMetagenome")

colors <- c("#b1728f","#c89cb0","#dfc6d2","#efe2e8",
            "#E69138","#edb273","#f5d3af","#fae9d7",
            "#bc3e47","#d0777e","#e4b1b5","#f1d8da",
            "#CBA92B","#dac26a","#eadcaa","#f4edd4",
            "#CD8987", "#CDACA1", "#DCC4BC", "#EADCD7",
            "#2C2C34", "#545463", "#7B7B8E",
            "#493C61",
            "#38761d","#739f60","#afc8a4","#d7e3d1",
            "#3B7D6A", "#59B198","#82C4B2", "#ACD8CC",
            "#3E5641",
            "#073763","#517391","#9bafc0","#cdd7df","#E6EBEF", 
            "#4861AD")


genus <- c(
  # Actinomycetota
           "Cutibacterium","Corynebacterium", "Citricoccus", "Micrococcus",
           "Kocuria","Rothia", "Brevibacterium","Gordonia",
           "Dermabacter","Kytococcus", "Janibacter","Dietzia",
           "Microbacterium","Brachybacterium","Dermacoccus","Nesterenkonia",
           "Pseudoclavibacter","Helcococcus", "Cellulosimicrobium", "Micromonospora", 
           "Rhodococcus", "Aestuariimicrobium", "Pseudoglutamicibacter",
 #Bacteroidota
           "Sphingobacterium",
 #Bacillota
           "Staphylococcus","Bacillus","Granulicatella","Lysinibacillus", 
           "Paenibacillus", "Enterococcus", "Niallia", "Oceanobacillus", 
           "Peribacillus",
 #Pseudomonadota
           "Klebsiella","Citrobacter","Enterobacter", "Raoultella", "Escherichia",
           "Morganella")

# Create a named vector mapping genera to colors
genus_colors <- setNames(colors, genus)

# Create a named vector for mapping
phylum_map <- c(
  # Actinomycetota
  "Cutibacterium" = "Actinomycetota",
  "Corynebacterium" = "Actinomycetota",
  "Citricoccus" = "Actinomycetota",
  "Micrococcus" = "Actinomycetota",
  "Kocuria" = "Actinomycetota",
  "Rothia" = "Actinomycetota",
  "Brevibacterium" = "Actinomycetota",
  "Gordonia" = "Actinomycetota",
  "Dermabacter" = "Actinomycetota",
  "Kytococcus" = "Actinomycetota",
  "Janibacter" = "Actinomycetota",
  "Dietzia" = "Actinomycetota",
  "Microbacterium" = "Actinomycetota",
  "Brachybacterium" = "Actinomycetota",
  "Dermacoccus" = "Actinomycetota",
  "Nesterenkonia" = "Actinomycetota",
  "Pseudoclavibacter" = "Actinomycetota",
  "Helcococcus" = "Actinomycetota",
  "Cellulosimicrobium" = "Actinomycetota",
  "Micromonospora" = "Actinomycetota",
  "Rhodococcus" = "Actinomycetota",
  "Aestuariimicrobium" = "Actinomycetota",
  "Pseudoglutamicibacter" = "Actinomycetota",
  
  # Bacteroidota
  "Sphingobacterium" = "Bacteroidota",
  
  # Bacillota
  "Staphylococcus" = "Bacillota",
  "Bacillus" = "Bacillota",
  "Granulicatella" = "Bacillota",
  "Lysinibacillus" = "Bacillota",
  "Paenibacillus" = "Bacillota",
  "Enterococcus" = "Bacillota",
  "Niallia" = "Bacillota",
  "Oceanobacillus" = "Bacillota",
  "Peribacillus" = "Bacillota",
  
  # Pseudomonadota
  
  "Klebsiella" = "Pseudomonadota",
  "Citrobacter" = "Pseudomonadota",
  "Enterobacter" = "Pseudomonadota",
  "Raoultella" = "Pseudomonadota",
  "Escherichia" = "Pseudomonadota",
  "Morganella" = "Pseudomonadota"
)


```

## Load data

```{r Load datasets, include=FALSE}
# Culture dataset ----
culture <- read_excel("/Users/thynguyen/Documents/GitHub/SkinBioassayStudy1/SkinBioassayStudy/Figures/Final/Extended_Data_Fig_1/Data/251010_SupTable2_Updated.xlsx")

# Assign body and site types
culture <- culture %>%
  #filter(row_number() !=1) %>%
  #row_to_names(row_number = 1) %>%
  mutate(body_site = case_when(
    `Body site` == "Antecubital fossa" ~ "Af", 
    `Body site` == "Alar crease" ~ "Al", 
    `Body site` == "Occiput" ~ "Oc", 
    `Body site` == "Nares" ~ "Na", 
    `Body site` == "Toe web space" ~ "Tw", 
    `Body site` == "Volar forearm" ~ "Vf",
    `Body site` == "Back" ~ "Ba",
    `Body site` == "Umbilicus" ~ "Um",
    TRUE ~ "NA"
  )) %>%
  relocate(body_site, .after =`Body site`) %>%
  mutate(site_type = case_when(
    `Body site` == "Antecubital fossa" ~ "Rarely Moist", 
    `Body site` == "Alar crease" ~ "Sebaceous", 
    `Body site` == "Occiput" ~ "Sebaceous", 
    `Body site` == "Nares" ~ "Moist", 
    `Body site` == "Toe web space" ~ "Moist", 
    `Body site` == "Volar forearm" ~ "Rarely Moist",
    `Body site` == "Back" ~ "Sebaceous",
    `Body site` == "Umbilicus" ~ "Moist",
    TRUE ~ "NA"
  )) %>%
  relocate(site_type, .after =body_site) 

# Summarize culture data
culture_final <- culture %>%
  filter(Genus != "Penicillium") %>%
  group_by(Genus, body_site, site_type) %>%
  dplyr::summarise(
    count = n(),
    .groups = "drop"
  ) %>%
  group_by(body_site) %>%
  mutate(
    total_body_site_count = sum(count),
    rel_abun = (count / total_body_site_count) * 100
  ) %>%
  ungroup() %>%
  mutate(dataset =  "Culture") %>% 
  relocate(dataset, .before =1) %>%
  mutate(Genus = case_when(
    is.na(Genus) | Genus == "" ~ "Other",
    TRUE ~ Genus
  )) %>%
  dplyr::rename("genus" = "Genus") %>%
  select(dataset, genus, body_site, site_type, rel_abun)

# Metagenome (Sylph and Kraken) ----
metagenome <- read_csv("/Users/thynguyen/Documents/GitHub/SkinBioassayStudy1/SkinBioassayStudy/Figures/Final/Extended_Data_Fig_1/Data/Sylph_Kraken_RelAbun 2.csv")

# Summarize metagenome data
metagenome_final <- metagenome %>%
  group_by(genus1, body_site, site_type) %>%
  dplyr::summarise(
    mean_abundance_sylph = mean(rel_abun_sylph, na.rm = TRUE),
    mean_abundance_kraken = mean(rel_abun_kraken, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(mean_abundance_kraken = if_else(is.nan(mean_abundance_kraken), 0, mean_abundance_kraken)) %>%
  pivot_longer(
    cols = c(mean_abundance_sylph, mean_abundance_kraken),
    names_to = "dataset",
    values_to = "rel_abun"
  ) %>%
  mutate(dataset = case_when(
    dataset == "mean_abundance_sylph" ~ "Sylph",
    dataset == "mean_abundance_kraken" ~ "Kraken",
    TRUE ~ dataset
  )) %>%
  dplyr::rename("genus" = "genus1") %>%
  select(dataset, genus, body_site, site_type, rel_abun)

# Combine metagenomic and culture data
combined <- rbind(metagenome_final, culture_final)

# By genus ----
# Summarize culture data
culture_final_genus <- culture_final %>%
  group_by(dataset, genus) %>%
  dplyr::summarise(
    rel_abun = mean(rel_abun, na.rm=T), 
    .groups = "drop"
  )

metagenome_final_genus <- metagenome_final %>%
  filter(!dataset == "Sylph") %>%
  group_by(dataset, genus) %>%
  dplyr::summarise(
    rel_abun = mean(rel_abun, na.rm=T), 
    .groups = "drop"
  )

# Combine data
combined_genus <- rbind(culture_final_genus, metagenome_final_genus)

# Determine presence in each dataset
combined_genus_presence <- combined_genus %>%
  filter(rel_abun > 0) %>%
  distinct(dataset, genus) %>%
  mutate(present = 1) %>%
  pivot_wider(names_from = dataset, 
              values_from = present, 
              values_fill = 0) %>%
  filter(!genus == "Other")

abundance_stats_genus <- combined_genus %>%
  group_by(dataset, genus) %>%
  dplyr::summarise(
    mean_abundance = mean(rel_abun, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  pivot_wider(
    names_from = dataset,
    values_from = mean_abundance,
    values_fill = 0
  ) %>%
  filter(!genus == "Other") 
  
# Combine the datasets
presence_abundance_genus <- combined_genus_presence %>%
  dplyr::left_join(abundance_stats_genus, by = c("genus")) %>%
  dplyr::rename("Kraken" = "Kraken.x", 
         "Culture" = "Culture.x", 
         "Kraken_abundance" = "Kraken.y", 
         "Culture_abundance" = "Culture.y")

# Overlapping taxa
intersection_taxa_genus <- presence_abundance_genus %>%
  filter(Culture == 1) %>%
  #filter(Culture == 1 & Kraken ==1) %>%
  select(genus)
# Join data
intersection_data_genus <- presence_abundance_genus %>%
  dplyr::inner_join(intersection_taxa_genus, by = c("genus")) %>%
  dplyr::mutate(
    Culture_abundance = Culture_abundance / 100,
    Kraken_abundance = Kraken_abundance / 100
  ) %>%
  dplyr::rename(
    iso_abun = Culture_abundance,
    met_abun = Kraken_abundance
  )

# Map genus to phylum
intersection_data_genus$phylum <- phylum_map[intersection_data_genus$genus]

# reorder columns
intersection_data_genus <- intersection_data_genus %>%
  select(genus, phylum, met_abun, iso_abun)

# Export data for Figure 2B
#write_csv(intersection_data_genus, "/Users/thynguyen/Documents/GitHub/SkinBioassayStudy/Figures/Final/Figure2/Data/scat_plot_updated2.csv")
```

## Plots

```{r Upset Plot}
# Input data for upset plot
# By genus, body_site, site_type ----
upset_presence <- combined %>%
  filter(!dataset == "Sylph") %>%
  #filter(!dataset == "Kraken") %>%
  filter(rel_abun > 0) %>%
  distinct(dataset, body_site, site_type, genus) %>%
  mutate(present = 1) %>%
  pivot_wider(names_from = dataset, 
              values_from = present, 
              values_fill = 0) %>%
  filter(!genus == "Other")

# Abundance statistics for each genus across datasets
abundance_stats <- combined %>%
  filter(!dataset == "Sylph") %>%
  #filter(!dataset == "Kraken") %>%
  group_by(genus, body_site, site_type, dataset) %>%
  dplyr::summarise(
    mean_abundance = mean(rel_abun, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  pivot_wider(
    names_from = dataset,
    values_from = mean_abundance,
    values_fill = 0
  ) %>%
  filter(!genus == "Other") 
  

# Combine the datasets - Kraken
upset_data <- upset_presence %>%
  dplyr::left_join(abundance_stats, by = c("genus", "body_site", "site_type")) %>%
  dplyr::rename("Kraken" = "Kraken.x", 
         "Culture" = "Culture.x", 
         "Kraken_abundance" = "Kraken.y", 
         "Culture_abundance" = "Culture.y")

# Combine the datasets - Sylph
#upset_data <- upset_presence %>%
#  dplyr::left_join(abundance_stats, by = c("genus", "body_site", "site_type")) %>%
#  dplyr::rename("Sylph" = "Sylph.x", 
#         "Culture" = "Culture.x", 
#         "Sylph_abundance" = "Sylph.y", 
#         "Culture_abundance" = "Culture.y")

# Format 0/1 as numeric
#upset_data <- upset_data %>%
#  mutate(
#    Sylph = as.numeric(Sylph),
#    Kraken = as.numeric(Kraken), 
#    Culture = as.numeric(Culture)
#  ) %>%
  # Filter out rows if both column have < 0.0001
#  filter(Kraken_abundance >= 0.0001 | Sylph_abundance >= 0.0001) # 2361 taxa remaining

# Use this one
#upset_data <- upset_data %>%
#  mutate(
#    Sylph = as.numeric(Sylph),
#    Kraken = as.numeric(Kraken), 
#    Culture = as.numeric(Culture)
#  ) %>%
  # Filter out rows if either column have < 0.0001
#  filter(Kraken_abundance >= 0.0001,  Sylph_abundance >= 0.0001) # 1084 taxa remaining

# Use this one
upset_data1 <- upset_data %>%
  mutate(
    Kraken = as.numeric(Kraken), 
    Culture = as.numeric(Culture)
  ) %>%
  # Filter out rows if either column have < 0.01%
  filter(Kraken_abundance >= 0.0001) # 1981 taxa remaining

#upset_data2 <- upset_data %>%
#  mutate(
#    Sylph = as.numeric(Sylph), 
#    Culture = as.numeric(Culture)
#  ) %>%
  # Filter out rows if either column have < 0.001
#  filter(Sylph_abundance >= 0.0001) # 827 taxa remaining filtering out < 0.005 abundance; 1464 taxa for < 0.0001


# Plot
#upset(
#  upset_data, 
#  intersect = c("Culture", "Sylph", "Kraken"),
#  name = "",
#  width_ratio = 0.1,
#  min_size = 1,
#  max_degree = 3,
#  base_annotations = list(
#    "Taxa Count" = intersection_size(
#      counts = TRUE,
#      text = list(size = 3)
#    )
#  ),
  
  # Add side plots for abundance
#  stripes = upset_stripes(
#    geom = geom_segment(size = 6),
#    colors = c("white", "grey95")
#  ),
  
  # Change set size
#  set_sizes = upset_set_size() + 
#    theme(
#      axis.text.x = element_text(angle = 45, hjust = 1),
#      axis.title.x = element_blank()
#    ),
  
  # Add custom annotations
#  annotations = list(
#    "Culture abundance" = (
#      ggplot(mapping = aes(y = Culture_abundance)) +  
#        geom_boxplot(fill = "#b1728f", alpha = 0.7) +
#        theme_minimal() +
#        labs(y = "Culture abundance")
#    ),
#    "Sylph abundance" = (
#      ggplot(mapping = aes(y = Sylph_abundance)) +  
#        geom_boxplot(fill = "#38761d", alpha = 0.7) +
#        theme_minimal() +
#        labs(y = "Sylph abundance")
#    ),
#    "Kraken abundance" = (
#      ggplot(mapping = aes(y = Kraken_abundance)) +  
#        geom_boxplot(fill = "#073763", alpha = 0.7) +
#        theme_minimal() +
#        labs(y = "Kraken abundance")
#    )
#  )
#)

# Kraken - 100 overlapping taxa
upset(
  upset_data1, 
  intersect = c("Culture", "Kraken"),
  name = "",
  width_ratio = 0.1,
  min_size = 1,
  max_degree = 3,
  base_annotations = list(
    "Taxa Count" = intersection_size(
      counts = TRUE,
      text = list(size = 3)
    )
  ),
  
  # Add side plots for abundance
  stripes = upset_stripes(
    geom = geom_segment(size = 6),
    colors = c("white", "grey95")
  ),
  
  # Change set size
  set_sizes = upset_set_size() + 
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1),
      axis.title.x = element_blank()
    ),
  
  # Add custom annotations
  annotations = list(
    "Culture abundance" = (
      ggplot(mapping = aes(y = Culture_abundance)) +  
        geom_boxplot(fill = "#b1728f", alpha = 0.7) +
        theme_minimal() +
        labs(y = "Culture abundance")
    ),
    "Kraken abundance" = (
      ggplot(mapping = aes(y = Kraken_abundance)) +  
        geom_boxplot(fill = "#073763", alpha = 0.7) +
        theme_minimal() +
        labs(y = "Kraken abundance")
    )
  )
)

# Plot without boxplot
upset(
  upset_data1, 
  intersect = c("Culture", "Kraken"),
  name = "",
  width_ratio = 0.1,
  min_size = 1,
  max_degree = 3,
  base_annotations = list(
    "Taxa Count" = intersection_size(
      counts = TRUE,
      text = list(size = 3)
    )
  ),
  
  # Add side plots for abundance
  stripes = upset_stripes(
    geom = geom_segment(size = 6),
    colors = c("white", "grey95")
  ),
  
  # Change set size
  set_sizes = upset_set_size() + 
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1),
      axis.title.x = element_blank()
    )
)

# By genus ----
# Input data for upset plot
upset_presence_genus <- combined %>%
  filter(!dataset == "Sylph") %>%
  #filter(!dataset == "Kraken") %>%
  filter(rel_abun > 0) %>%
  distinct(dataset, genus) %>%
  mutate(present = 1) %>%
  pivot_wider(names_from = dataset, 
              values_from = present, 
              values_fill = 0) %>%
  filter(!genus == "Other")

# Abundance statistics for each genus across datasets
abundance_stats_genus <- combined %>%
  filter(!dataset == "Sylph") %>%
  #filter(!dataset == "Kraken") %>%
  group_by(genus, dataset) %>%
  dplyr::summarise(
    mean_abundance = mean(rel_abun, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  pivot_wider(
    names_from = dataset,
    values_from = mean_abundance,
    values_fill = 0
  ) %>%
  filter(!genus == "Other") 
  

# Combine the datasets - Kraken
upset_data_genus <- upset_presence_genus %>%
  dplyr::left_join(abundance_stats_genus, by = c("genus")) %>%
  dplyr::rename("Kraken" = "Kraken.x", 
         "Culture" = "Culture.x", 
         "Kraken_abundance" = "Kraken.y", 
         "Culture_abundance" = "Culture.y")

# Filter those with < 0.001%
upset_data1_genus <- upset_data_genus %>%
  mutate(
    Kraken = as.numeric(Kraken), 
    Culture = as.numeric(Culture)
  ) %>%
  # Filter out rows if either column have < 0.001%
  filter(Kraken_abundance >= 0.001) # 223 genera remaining

# Kraken
# 32 overlapping genus
# 232 only detected in Kraken
# 9 only detected in culture
upset(
  upset_data_genus, 
  intersect = c("Culture", "Kraken"),
  name = "",
  width_ratio = 0.1,
  min_size = 1,
  max_degree = 3,
  base_annotations = list(
    "Genera Count" = intersection_size(
      counts = TRUE,
      text = list(size = 3)
    )
  ),
  
  # Add side plots for abundance
  stripes = upset_stripes(
    geom = geom_segment(size = 6),
    colors = c("white", "grey95")
  ),
  
  # Change set size
  set_sizes = upset_set_size() + 
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1),
      axis.title.x = element_blank()
    ),
  
  # Add custom annotations
  annotations = list(
    "Culture abundance" = (
      ggplot(mapping = aes(y = Culture_abundance)) +  
        geom_boxplot(fill = "#b1728f", alpha = 0.7) +
        theme_minimal() +
        labs(y = "Culture abundance (%)")
    ),
    "Kraken abundance" = (
      ggplot(mapping = aes(y = Kraken_abundance)) +  
        geom_boxplot(fill = "#073763", alpha = 0.7) +
        theme_minimal() +
        labs(y = "Kraken abundance (%)")
    )
  )
)

# Plot without boxplot
upset(
  upset_data_genus, 
  intersect = c("Culture", "Kraken"),
  name = "",
  width_ratio = 0.1,
  min_size = 1,
  max_degree = 3,
  base_annotations = list(
    "Taxa Count" = intersection_size(
      counts = TRUE,
      text = list(size = 6)
    ) + theme(
      axis.text.y = element_text(size = 12), 
      axis.title.y = element_text(size = 14)
    )
  ),
  
  themes = upset_default_themes(
    text = element_text(size = 12)
  ), 
  
  # Change set size
  set_sizes = upset_set_size() + 
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1, size = 12),
      axis.title.x = element_blank()
    )
)

# Sylph
#upset(
#  upset_data2, 
#  intersect = c("Culture", "Sylph"),
#  name = "",
#  width_ratio = 0.1,
#  min_size = 1,
#  max_degree = 3,
#  base_annotations = list(
#    "Taxa Count" = intersection_size(
#      counts = TRUE,
#      text = list(size = 3)
#    )
#  ),
  
  # Add side plots for abundance
#  stripes = upset_stripes(
#    geom = geom_segment(size = 6),
#    colors = c("white", "grey95")
#  ),
  
  # Change set size
#  set_sizes = upset_set_size() + 
#    theme(
#      axis.text.x = element_text(angle = 45, hjust = 1),
#      axis.title.x = element_blank()
#    ),
  
  # Add custom annotations
#  annotations = list(
#    "Culture abundance" = (
#      ggplot(mapping = aes(y = Culture_abundance)) +  
#        geom_boxplot(fill = "#b1728f", alpha = 0.7) +
#        theme_minimal() +
#        labs(y = "Culture abundance")
#    ),
#    "Sylph abundance" = (
#      ggplot(mapping = aes(y = Sylph_abundance)) +  
#        geom_boxplot(fill = "#38761d", alpha = 0.7) +
#        theme_minimal() +
#        labs(y = "Sylph abundance")
#    )
#  )
#)
```

## Intersection

```{r Overlapping/Correlation Plots}
# Overlapping taxa
intersection_taxa <- upset_data %>%
  filter(Culture == 1) %>%
  #filter(Culture == 1 & Kraken ==1) %>%
  select(genus, body_site, site_type)
# Join data
intersection_data <- upset_data %>%
  dplyr::inner_join(intersection_taxa, by = c("genus", "body_site", "site_type"))

# Set factor
intersection_data$genus <- factor(intersection_data$genus, levels = genus)

# Scatterplot - Sylph ----
#intersection_data %>%
#  mutate(body_site = factor(body_site, levels = c("Al","Ba", "Oc", "Na", "Um","Tw", "Vf", "Af"))) %>%
#  ggplot(aes(x = Culture_abundance/100, y = Sylph_abundance/100, color = genus)) +
#  geom_point(alpha = 0.7, size = 3) +
#  geom_smooth(method = "lm", color = "black", linetype = "dashed", se = TRUE, alpha = 0.2) +
#  stat_cor(
#    method = "spearman",
#    label.x.npc = 0.1,  
#    label.y.npc = 1, 
#    size = 5,   
#    color = "black" 
#  ) +
#  scale_color_manual(values = genus_colors) +
#  scale_shape_manual(
  #values = c(
  #  "Af" = 16,  # filled circle
  #  "Al" = 17,  # filled triangle up
  #  "Ba" = 15,  # filled square
  #  "Na" = 18,  # filled diamond
  #  "Oc" = 8,   # asterisk/star
  #  "Tw" = 3,   # plus
  #  "Um" = 4,   # X
  #  "Vf" = 7    # square cross
  #),
#  name = "Body Site"
#) +
  #geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "gray50") +
#  scale_x_log10(
   # breaks = c(0.001, 0.01, 0.1, 1),
   # labels = c("0.001", "0.01", "0.1", "1")
#  ) +
#  scale_y_log10(
   # breaks = c(0.001, 0.01, 0.1, 1),
   # labels = c("0.001", "0.01", "0.1", "1")
#  ) +
#  labs(
#    title = NULL,
#    x = "Culture abundance",
#    y = "Sylph abundance"
#  ) +
#  theme_minimal(base_size = 18) +
#  theme(
#    panel.grid.minor = element_blank(), 
#    axis.text.x = element_text(angle = 45, hjust = 1)) +
#  guides(color = guide_legend(ncol = 1)) +
#  facet_wrap(~ body_site, scales = "fixed")


# Scatterplot - Kraken ----
intersection_data %>%
  #filter(!genus == "Cutibacterium") %>%
  mutate(body_site = factor(body_site, levels = c("Al","Ba", "Oc", "Na", "Um","Tw", "Vf", "Af"))) %>%
  ggplot(aes(x = Culture_abundance/100, y = Kraken_abundance/100, color = genus)) +
  geom_point(alpha = 0.7, size = 3) +
  geom_smooth(method = "lm", color = "black", linetype = "dashed", se = TRUE, alpha = 0.2) +
  stat_cor(
    method = "spearman",
    label.x.npc = 0.1,  
    label.y.npc = 1, 
    size = 5,   
    color = "black" 
  ) +
  scale_color_manual(values = genus_colors) +
  scale_shape_manual(
  #values = c(
  #  "Af" = 16,  # filled circle
  #  "Al" = 17,  # filled triangle up
  #  "Ba" = 15,  # filled square
  #  "Na" = 18,  # filled diamond
  #  "Oc" = 8,   # asterisk/star
  #  "Tw" = 3,   # plus
  #  "Um" = 4,   # X
  #  "Vf" = 7    # square cross
  #),
  name = "Body Site"
) +
  #geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "gray50") +
  scale_x_log10(
   # breaks = c(0.001, 0.01, 0.1, 1),
   # labels = c("0.001", "0.01", "0.1", "1")
  ) +
  scale_y_log10(
   # breaks = c(0.001, 0.01, 0.1, 1),
   # labels = c("0.001", "0.01", "0.1", "1")
  ) +
  labs(
    title = NULL,
    x = "Isolate relative abundance",
    y = "Metagenomic relative abundance"
  ) +
  theme_minimal(base_size = 18) +
  theme(
    panel.grid.minor = element_blank(), 
    axis.text.x = element_text(angle = 45, hjust = 1)) +
  guides(color = guide_legend(ncol = 1)) +
  facet_wrap(~ body_site, scales = "fixed")

```
