---
title: "Culture vs Metagenome Comparison"
author: "Thy Nguyen"
date: "`r Sys.Date()`"
output: html_document
---

```{r Load packages, include=FALSE}
library(tidyverse)
library(readxl)
library(readr)
library(ggplot2)
library(dplyr)
library(janitor)

```

```{r Load sylph results, include=FALSE}
# Metagenomic dataset
data <- read.delim("/Users/thynguyen/Downloads/sylph_results.txt", header=FALSE)

data1 <- data %>% 
  dplyr::rename(
    sample = V1, 
    body_site = V2, 
    site_type = V3, 
    gtdb = V4, 
    taxa = V5, 
    rel_abun = V6
  ) %>%
  separate(taxa, 
           into = c("domain", "phylum", "class", "order", "family", "genus", "species"), 
           sep = ";", 
           remove = FALSE) %>%
  mutate(across(c(domain, phylum, class, order, family, genus, species), 
                ~sub("^[a-z]__", "", .))) %>%
  mutate(genus1 = sub("_[A-Za-z0-9].*$", "", genus))

# Calculate genus abundance
genus_abundance <- data1 %>%
  group_by(sample, genus1, body_site, site_type) %>%
  summarise(total_rel_abun = sum(rel_abun, na.rm = TRUE)) %>%
  arrange(desc(total_rel_abun))

# Filter based on 0.1% abundance and 5% prevalence
total_samples <- length(unique(data1$sample))
genus_summary <- data1 %>%
  # Create clean genus column
  mutate(genus1 = sub("_[A-Za-z0-9].*$", "", genus)) %>%
  # Group by sample, genus to get abundance per sample
  group_by(sample, family, genus, genus1, body_site, site_type) %>%
  summarise(sample_genus_abun = sum(rel_abun, na.rm = TRUE), .groups = "keep") %>%
  # Calculate presence count and determine if genus meets criteria
  group_by(family, genus, genus1) %>%
  mutate(
    meets_abundance = sample_genus_abun >= 0.001, # at least 0.1% abundance or greater
    presence_count = sum(meets_abundance),
    prevalence_threshold = total_samples * 0.05, # found in at least 5% of metagenomes or more
    keep_separately = presence_count > prevalence_threshold
  )

sample_with_other <- genus_summary %>%
  mutate(
    genus2 = case_when(
      # Grouping less than 0.1% abundance taxa and ones found in at least 5% of metagenomes into Other
      keep_separately & sample_genus_abun >= 0.001 ~ genus1,
      TRUE ~ "Other"
    ), 
    genus2 = case_when(
      is.na(genus2) | genus2 == "" ~ "Rhizobiaceae",
      genus2 == "28L" ~ "Megasphaeraceae",
      TRUE ~ genus2
    )
  ) %>%
  group_by(sample, family, genus2, body_site, site_type) %>%
  summarise(
    combined_abundance = sum(sample_genus_abun, na.rm = TRUE),
    .groups = "keep"
  )

genus_abundance_final <- sample_with_other %>%
  group_by(genus2, body_site, site_type) %>%
  summarise(
    rel_abun = mean(combined_abundance, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  arrange(desc(ifelse(genus2 == "Other", -1, rel_abun))) %>%
  mutate(dataset =  "Metagenomic") %>% 
  relocate(dataset, .before =1) %>%
  rename("genus" = "genus2")

```

```{r Load culture dataset, include=FALSE}
# Culture dataset
culture <- read_excel("/Users/thynguyen/Downloads/Sup Tables (1).xlsx", 
    sheet = "Table S2 - Updated")

# Assign body and site types
culture <- culture %>%
  filter(row_number() !=1) %>%
  row_to_names(row_number = 1) %>%
  mutate(body_site = case_when(
    `Body site` == "Antecubital fossa" ~ "Af", 
    `Body site` == "Alar crease" ~ "Al", 
    `Body site` == "Occiput" ~ "Oc", 
    `Body site` == "Nares" ~ "Na", 
    `Body site` == "Toe web space" ~ "Tw", 
    `Body site` == "Volar forearm" ~ "Vf",
    `Body site` == "Back" ~ "Ba",
    `Body site` == "Umbilicus" ~ "Um",
    TRUE ~ "NA"
  )) %>%
  relocate(body_site, .after =`Body site`) %>%
  mutate(site_type = case_when(
    `Body site` == "Antecubital fossa" ~ "Rarely Moist", 
    `Body site` == "Alar crease" ~ "Sebaceous", 
    `Body site` == "Occiput" ~ "Sebaceous", 
    `Body site` == "Nares" ~ "Moist", 
    `Body site` == "Toe web space" ~ "Moist", 
    `Body site` == "Volar forearm" ~ "Rarely Moist",
    `Body site` == "Back" ~ "Sebaceous",
    `Body site` == "Umbilicus" ~ "Moist",
    TRUE ~ "NA"
  )) %>%
  relocate(site_type, .after =body_site) 

# Summarize culture data
culture_final <- culture %>%
  group_by(Genus, body_site, site_type) %>%
  summarise(
    count = n(),
    .groups = "drop"
  ) %>%
  group_by(body_site) %>%
  mutate(
    total_body_site_count = sum(count),
    rel_abun = count / total_body_site_count
  ) %>%
  ungroup() %>%
  mutate(dataset =  "Culture") %>% 
  relocate(dataset, .before =1) %>%
  mutate(Genus = case_when(
    is.na(Genus) | Genus == "" ~ "Other",
    TRUE ~ Genus
  ))
  
```


```{r cars}
summary(cars)
```


```{r pressure, echo=FALSE}
plot(pressure)
```
